### ISSUE TITLE
Wrong port for exporter

### ISSUE THREAD

**Issue by onemanstartup** [yabeda-rb/yabeda-prometheus#1]
You chosen 9310 when this port is already allocated. 
You can see it here https://github.com/prometheus/prometheus/wiki/Default-port-allocations

Ruby Prometheus Exporter allocated for themselves 9394 maybe you can use that port or ask prometheus for your own.

PS. 

В чате в телеграме rubyшном @Envek как можно найти? Есть же наверное. Просто я не понимаю пока бенефитов по сравнению с promeheus_exporter. Он так же работает как экспортер, я его запускаю в докере, в swarm. Хотя не сказал бы что я проверял корректность сбора метрик 😃

**Comment by Envek** [comment]
Good point about default port number. Will change to 9394 (as we're targeting as a replacement). Can't remember why we're using 9310.

**Comment by onemanstartup** [comment]
@Envek you forgot to change in readme :)
