### ISSUE TITLE
Support store_settings option

### ISSUE THREAD

**Issue by Arkweid** [yabeda-rb/yabeda-prometheus#10]
Prometheus define new settings for metrics _store_setting_
https://github.com/prometheus/client_ruby#aggregation-settings-for-multi-process-stores

It would be nice to adapt metrics(**store_settings: metric.store** added):
https://github.com/yabeda-rb/yabeda-prometheus/blob/master/lib/yabeda/prometheus/adapter.rb
```ruby
    def register_gauge!(metric)
      validate_metric!(metric)
      registry.gauge(build_name(metric), docstring: metric.comment, labels: Array(metric.tags), store_settings: metric.store)
    end
```

**Comment by Envek** [comment]
I've released yabeda 0.5 and yabeda-prometheus 0.5 with support for metric aggregation with following syntax in the Yabeda metric declaration:

```ruby
group :some do
  gauge :tasks do
    comment "Number of test tasks"
    aggregation :max
  end
end
```

Please try it and share your thoughts!

However, be aware of stale metrics that can appear when you're using prometheus' direct file store. See https://github.com/prometheus/client_ruby/issues/109, https://github.com/prometheus/client_ruby/pull/173, and https://github.com/yabeda-rb/yabeda-puma-plugin/issues/8
