### ISSUE TITLE
Make webrick logger configurable

### ISSUE THREAD

**Issue by shouichi** [yabeda-rb/yabeda-prometheus#17]
Background:

We run containers and collect their stdout/stderr using a log collecting agent. The agent marks stderr as error logs. `Yabeda::Prometheus::Exporter` internally uses `Rack::CommonLogger` without passing logger. In this case `Rack::CommonLogger` logs to stderr. As a result, simple webrick logs are marked as errors in our environment.

Possible solutions:

- Enable to pass logger to `Rack::CommonLogger`
- Enable to configure the entire rack app

Thanks in advance.

**Comment by Envek** [comment]
Fixed in #19 and released in [0.8.0](https://github.com/yabeda-rb/yabeda-prometheus/releases/tag/v0.8.0) (please note that logging now is disabled by default)

**Comment by shouichi** [comment]
Thank you!
