### ISSUE TITLE
How do I make it work with multiple pods?

### ISSUE THREAD

**Issue by michudzik** [yabeda-rb/yabeda-prometheus#24]
Hey!

I've got a question. How do I setup the exporter if I expect more than one K8s pod in a deployment? As far as I understand, the `yabeda-sidekiq` configuration starts an exporter server when `sidekiq` is invoked. That means that on one pod, we will have one instance of the exporter running.

What happens when there are multiple pods running the same queue (basically a K8s deployment with 2-3 replicas). How do I fetch the metrics from all of the pods, rather than only one? 

Basic K8s service isn't a way to go here as it acts as a load balancer, so if I request /metrics on ClusterIP service, it will only return metrics from one exporter instance. How do I go about that? Any advice?

<img width="751" alt="image" src="https://user-images.githubusercontent.com/25963248/230648404-146e9744-d4c6-4527-8106-42b071c387b2.png">

**Comment by Envek** [comment]
Hey! Use [PodMonitor](https://prometheus-operator.dev/docs/operator/api/#monitoring.coreos.com/v1.PodMonitor) to let Prometheus Operator dynamically discovery all Sidekiq pods and scrape each pod individually.

See blog posts like this for details: https://alexandrev.medium.com/prometheus-concepts-servicemonitor-and-podmonitor-8110ce904908

**Comment by michudzik** [comment]
![giphy](https://user-images.githubusercontent.com/25963248/230792269-54166452-cbb6-44b8-b525-7860a4a42a19.gif)
