### ISSUE TITLE
About the multi-process support

### ISSUE THREAD

**Issue by elct9620** [yabeda-rb/yabeda-prometheus#4]
Hi, there

I test `yabeda-promtheus` with Passenger, but it seems not working. But the local machine is working well with puma.

After I read the source code, I guess it has some problem when running with a multi-process web server.

In this case, I think to add an option for the user to choose use `concurrent-ruby` in memory or cache the metrics in another server, ex. redis.

> I read the source code about the ActionCable one year ago, it also uses Redis (or PostgreSQL) to share some connection information between process/server. So I think add Redis support is a good idea.

**Comment by imella** [comment]
@Envek Did you manage to make it work on a Passenger running app?

I changed Passenger's config to only allow one process running (`--max-pool-size 1` and `--min-instances 1`) but it didn't work.

Maybe i'm forgetting something.

Great work on yabeda by the way!

**Comment by elct9620** [comment]
@leshik 

After I compare ` prometheus_exporter` and `prometheus-client-mmap`, the point I care about is I didn't want to run another process to share the metrics information, because my application is small and more flexible if I mount it on Rails.

In this case, I think `prometheus-client-mmap` provides the lightweight option for users who didn't want to run another process to handle it.

**Comment by Envek** [comment]
@elct9620, try to use yabeda-prometheus with GitLab's gem:

```ruby
# Gemfile
gem "prometheus-client-mmap"
gem "yabeda-prometheus"
```

Please note that [you need to specify `prometheus_multiproc_dir` for it](https://gitlab.com/gitlab-org/prometheus-client-mmap/blob/c1bddf6aec2e322295e2d5fd429ec42f4da76abe/lib/prometheus/client/configuration.rb#L12) to work:

```
prometheus_multiproc_dir=/tmp
```

**Comment by elct9620** [comment]
@Envek 

It seems not work.

In my production environment (Passenger) didn't generate any mmap file in /tmp. I guess it is Passenger problem, so I test it on my mac use `puma -w 3` to create multiple processes with puma.

But I still got the same result, if I use `puma` the result is correct, but if I use `puma -w 3` it didn't generate any mmap file and I cannot share metrics between process.

**Comment by dsalahutdinov** [comment]
Hey! support of gitlab client moved to another gem https://github.com/yabeda-rb/yabeda-prometheus-mmap
Try it out.

**Comment by Envek** [comment]
Closing this issue, as official Prometheus Ruby client got pretty good support for metrics aggregation via `DirectFileStore` (there are caveats however). See https://github.com/prometheus/client_ruby#data-stores
