### ISSUE TITLE
Support prometheus summary metric type

### ISSUE THREAD

**Issue by mikz** [yabeda-rb/yabeda-prometheus#5]
Would be great to support the [summary metric type](https://prometheus.io/docs/concepts/metric_types/#summary).
It is already supported in the [prometheus-client](https://github.com/prometheus/client_ruby#summary).

I'm ok with making a PR, any recommendation on how to approach this? This type is not exposed in the base yabeda gem.

**Comment by Envek** [comment]
Yes, most probably you need add it to base gem too.

The problem with summary is that it is prometheus-specific. Other monitoring systems doesn't differentiate them, and some of them doesn't differentiate metric types at all at their APIs, for example NewRelic calculates something like prometheus' summary values for every submitted metric not matter how it will be used.

From the one hand I don't want to make Yabeda API too prometheus-centric (despite the fact it was born from an DSL over prometheus-client), from the other – I want to give ability to customize metric implementation for adapters.

For now you can create PR in this repo and core yabeda repo. I will think about possible solutions meanwhile.

**Comment by Envek** [comment]
Released summary support in [yabeda 0.12.0](https://github.com/yabeda-rb/yabeda/releases/tag/v0.12.0) and [yabeda-prometheus 0.9.0](https://github.com/yabeda-rb/yabeda-prometheus/releases/tag/v0.9.0). Thanks for opening the issue and sorry for the long wait!
